FROM siya/php7:latest
COPY sources.list /etc/apt/
COPY site.conf /etc/nginx/sites-enabled/default
COPY cronfile /etc/cron.d/cronfile
RUN crontab /etc/cron.d/cronfile
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
WORKDIR /var/www/html
CMD service cron start && service nginx start && php-fpm