version: '3'
services:
  php:
    container_name: siya-blog-php
    build: ./
    volumes:
      - ../:/var/www/html
      - /data/siya-blog/volumes/storage:/var/www/html/storage
      - /data/siya-blog/volumes/vendor:/var/www/html/vendor
      - /data/siya-blog/volumes/nginx/logs:/var/log/nginx
    environment:
      TZ: Asia/Shanghai
